repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort src/ test/
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black src/ test/
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8 src/ test/
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy src/ test/
        types: [python]

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pipenv run pytest test/
        types: [python]

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run pytest --cov-report term-missing --cov=src/
        types: [python]